### ISSUE TITLE
i18n all views

### ISSUE THREAD

**Issue by robertoschwald** [Jasig/cas#1131] opened 2015-09-08 15:23 UTC
Some views currently keep hardcoded english texts:

    casAcceptableUsagePolicyView.jsp
    viewStatistics.jsp
    casPostReponseView.jsp
 
Shouldn’t we fully internationalize these as well? 
If yes, I send a PR.

**Comment by mmoayyed** [comment] 2015-09-08 15:26
Absolutely, every English text must be externalized. It's important that we have keys referring to all English text, but if we have the translations that would be of course better.

**Comment by mmoayyed** [comment] 2015-09-10 18:46
@robertoschwald Any progress on this? Not a blocker but it would be best to finalize it now that the GA date is coming up.

**Comment by leleuj** [comment] 2015-09-18 08:14
@mmoayyed Now that we have upgraded the CAS client in version 3.4.1, this is the last remaining issue, isn't it?

**Comment by leleuj** [comment] 2015-09-18 08:15
For the 4.1.0 release, I meant.

**Comment by mmoayyed** [comment] 2015-09-18 08:16
Yes. I intend to punt it, given we are really past the deadline. Can always go into 4.1.1

**Comment by mmoayyed** [comment] 2015-09-18 08:17
Bumped to 4.2.0

**Comment by mmoayyed** [comment] 2015-09-19 07:41
Closed. Duplicate of https://github.com/Jasig/cas/issues/678

**Closed by mmoayyed** 2015-09-19 07:41 UTC
Labels: Bug, Minor, Web
