### ISSUE TITLE
Single Sign Out callback not occuring for Proxy Tickets

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#519] opened 2014-07-15 06:29 UTC
I am using CAS Server 3.4.11 and am attempting to get single sign out to work. It all works fine for applications that are using service tickets, however, applications for which I am using proxy tickets aren’t getting the single sign out request. I stepped through the server code, and it appears that the initial TGT gets the expire() call, which calls all the service ticket services. However, the expire method for child PGTs isn’t being called. The PGT is getting removed from the db via the JpaTicketRegistry.deleteTicketAndChildren() call.

Environment: Linux, TC Server

Reported by: Richard Frazer, id: richard.frazer@sas.com

Created: Wed, 30 Jan 2013 08:24:44 -0700

Updated: Thu, 19 Jun 2014 11:36:29 -0700

JIRA: https://issues.jasig.org/browse/CAS-1255

The fix for this feature is of moderate effort and better suited to 4.x release schedule. Punting to 4.x per cas-dev discussion.

**Comment by antoine777** [comment] 2015-03-05 10:26
My CAS version is 3.4.11.
This issue is a serious problem for me because, in my company, almost all our internet services are authenticated by proxy tickets. When a user logout, we can't manage session invalidation for the proxified services.
You say this feature is a moderate effort but i don't know how to patch our CAS instance : can you explain how to fix this issue ?

**Comment by mmoayyed** [comment] 2015-03-05 12:44
It was a moderate fix around 2013. Not anymore. You'll need to create a separate expiration policy for proxy tickets, and have the cleaner possibly invoke the logout flow on proxy tickets. It's not a trivial fix.

**Comment by antoine777** [comment] 2015-03-12 14:24
I don't understand the suggested fix. The goal is to expire the proxy tickets when the user logout explicitely (by a /cas/logout request). We don't want to wait for the periodic cleaner to do the job (and actually, this is already done by the cleaner). 
Currently, when we make a logout request, CAS iterate over all the services of the TGT and call logOutOfService() method on each of them. 
Would it be possible to retrieve all the PGTs of a TGT and iterate over all the services of each PGT to do the same job ? 
But i don't see a way to retrive all the PGTs of a specific TGT : there is no TicketGrantingTicket#getPGTs() method : is this by design ?

**Comment by mmoayyed** [comment] 2015-03-12 14:41
>The goal is to expire the proxy tickets when the user logout explicitely 
I wouldn't say that's the goal. The goal would be to design expiration policies for PGTs and separate them from TGTs.

I'd recommend you point your question to the cas mailing lists first.

**Comment by antoine777** [comment] 2015-03-12 15:18
I've already post a question to https://groups.google.com/forum/#!topic/jasig-cas-user/oz4Pt_LsiTw but no answer...maybe this use case is not very common

**Comment by soulrenger** [comment] 2015-03-25 07:34
I don't know if my conditions fit this issues.I aleady post this to <https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!topic/jasig-cas-user/J7T2kda2MW4>
I just use Nginx to proxy my cas server,everything works fine when direct visit the cas server,but when I  try to visit the website through Nginx proxypass,sometimes the issuse happend as I posted above,when you use the manually type the logout url,the wesites works fine then.Hope some discussion or some lead,I don't have some clews.

**Comment by mmoayyed** [comment] 2015-12-16 17:00
@tduehr is this something I could interest you to review and possibly fix? :)

**Comment by tduehr** [comment] 2015-12-16 17:05
I want to say this was recently fixed in master but I'll give it a shot tonight.

**Comment by mmoayyed** [comment] 2016-01-08 09:13
Working on this. It's proving more difficult than I thought, but should have a PR ready today.

**Comment by tduehr** [comment] 2016-01-08 14:18
Sorry, I totally forgot about this...

**Comment by mmoayyed** [comment] 2016-01-08 14:19
No worries. I was in fact diagnosing some other issue and eventually arrived at this :) Please do a code review when you find the chance.

**Closed** 2016-01-12 07:27 UTC
Labels: Bug, Major, Ticket
